name: pdf_translator
description: App Flutter per aprire PDF e tradurre il testo selezionato.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

  
  
dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_pdfviewer: ^33.2.3
  file_picker: ^11.0.2
  http: ^1.6.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5
  epubx: ^4.0.0
  html_unescape: ^2.0.0
  scrollable_positioned_list: ^0.3.8
  image: ^3.3.0
  syncfusion_pdfviewer_platform_interface: ^33.2.12
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
